import { GameItem, SiteSettings } from './types';

export const INITIAL_GAMES: GameItem[] = [
  {
    id: 'game-1',
    title: 'GAME XX1',
    subtitle: 'VIP Cheat & Status Monitor System',
    version: 'v2.4.1 (Latest)',
    status: 'undetected',
    downloadUrl: 'https://drive.google.com/file/d/1ExampleGoogleDriveFileID1/view?usp=sharing',
    isDownloadEnabled: true,
    category: 'FPS / Action',
    updatedAt: '2026-09-15',
    bannerUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
    downloadCount: 12450,
    driveNote: 'รหัสแตกไฟล์ zip คือ: xx1vip (แนะนำให้ปิด Windows Defender ก่อนใช้งาน)',
  },
  {
    id: 'game-2',
    title: 'GAME XX2',
    subtitle: 'Mod Menu & Script Loader',
    version: 'v1.8.0',
    status: 'detected',
    downloadUrl: 'https://drive.google.com/file/d/1ExampleGoogleDriveFileID2/view?usp=sharing',
    isDownloadEnabled: false,
    category: 'Battle Royale',
    updatedAt: '2026-09-14',
    bannerUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=600&q=80',
    downloadCount: 8930,
    driveNote: 'สถานะแจ้งเตือน Detected! งดใช้งานชั่วคราวเพื่อความปลอดภัยของไอดีท่าน',
  },
  {
    id: 'game-3',
    title: 'GAME XX3',
    subtitle: 'Auto Farm & Quest Helper',
    version: 'v3.1.0',
    status: 'updating',
    downloadUrl: 'https://drive.google.com/file/d/1ExampleGoogleDriveFileID3/view?usp=sharing',
    isDownloadEnabled: false,
    category: 'MMORPG / RPG',
    updatedAt: '2026-09-15',
    bannerUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80',
    downloadCount: 5410,
    driveNote: 'กำลังอัปเดตระบบตามแพตช์เกมใหม่ คาดว่าจะเสร็จสิ้นเร็วๆ นี้',
  },
  {
    id: 'game-4',
    title: 'GAME XX4',
    subtitle: 'Skin Changer & Crosshair Tool',
    version: 'v1.0.5',
    status: 'undetected',
    downloadUrl: 'https://drive.google.com/file/d/1ExampleGoogleDriveFileID4/view?usp=sharing',
    isDownloadEnabled: true,
    category: 'Utilities',
    updatedAt: '2026-09-13',
    bannerUrl: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=600&q=80',
    downloadCount: 3200,
    driveNote: 'ใช้งานได้ปกติ 100% ไม่ต้องแตกไฟล์ สามารถดับเบิ้ลคลิกรันได้ทันที',
  }
];

export const INITIAL_SETTINGS: SiteSettings = {
  globalMaintenance: false,
  maintenanceMessage: 'ระบบปิดปรับปรุงชั่วคราวเพื่ออัปเดตความปลอดภัย โปรดกลับมาใหม่ในภายหลัง',
  announcementText: '🔥 อัปเดตแพตช์ใหม่รองรับเวอร์ชั่นล่าสุด! GAME XX1 สถานะ Undetected ปลอดภัย 100%',
  announcementActive: true,
  siteTitle: 'XX1 GAME HUB - ศูนย์รวมดาวน์โหลด & เช็คสถานะเกม',
  adminPassword: 'admin1234',
};
